"""
Update manual_ticker_mappings.json with new ticker data
Merges existing mappings with newly uploaded tickers
"""
import json
import re

# Load existing manual mappings
print("Loading existing manual mappings...")
with open('manual_ticker_mappings.json', 'r') as f:
    existing_mappings = json.load(f)

print(f"  Found {len(existing_mappings)} existing mappings")

# New mappings from uploaded file
new_mappings = {
    # First batch
    "AUTOMOBILE CORPORATION OF GOA LIMITED": "AUTOCORP.NS",
    "SINTEX PLASTICS TECHNOLOGY LIMITED": "SPTL.NS",
    "EVINIX ACCESSORIES LIMITED": "EVINIX.NS",
    "CANARA HSBC LIFE INSURANCE COMPANY LIMITED": "CANHLIFE.NS",
    "VASCON ENGINEERS LIMITED": "VASCONEQ.NS",
    "PENTAMEDIA GRAPHICS LTD.": "PENTSFWARE.NS",
    "GODREJ INDUSTRIES LIMITED": "GODREJIND.NS",
    "CORE HEALTHCARE LIMITED": "COREPARENT.NS",
    "SMS PHARMACEUTICALS LIMITED": "SMSPHARMA.NS",
    
    # Second batch
    "BEEYU OVERSEAS LIMITED": "532645.BO",
    "MEGHMANI ORGANICS LIMITED": "MOL.NS",
    "GTN INDUSTRIES LIMITED": "GTNIND.NS",
    "MAMATA MACHINERY LTD.": "MAMATA.NS",
    "MILLENNIUM ONLINE SOLUTIONS (INDIA) LIMITED": "511187.BO",
    "SHRI LAKSHMI COTSYN LIMITED": "533036.BO",
    "AVANCE TECHNOLOGIES LIMITED": "512149.BO",
    "HELIOS & MATHESAN INFORMATION TECHNOLOGY LTD": "HELIOSMATH.NS",
    "TATA CAPITAL LIMITED": "TATACAP.NS",
    
    # Third batch
    "NIIT LEARNING SYSTEMS LIMITED": "NIITMTS.NS",
    "J. K. CEMENT LIMITED.": "JKCEMENT.NS",
    "JUBILANT AGRI AND CONSUMER PRODUCTS LIMITED": "JUBLINDS.NS",
    "INDIA STEEL WORKS LIMITED": "ISWL.NS",
    "BAJAJ HINDUSTHAN SUGAR LIMITED": "BAJAJHIND.NS",
    "BAJAJ CONSUMER CARE LIMITED": "BAJAJCON.NS",
    "THE GREAT EASTERN SHIPPING COMPANY LIMITED": "GESHIP.NS",
    
    # Fourth batch
    "PIRAMAL FINANCE LIMITED": "PEL.NS",
    "ODIGMA CONSULTANCY SOLUTIONS LIMITED": "ODIGMA.NS",
    "RASHI PERIPHERALS LIMITED": "RPTECH.NS",
    "TATA TECHNOLOGIES LTD.": "TATATECH.NS",
    "BROADCAST INITIATIVES LIMITED": "BROADCAST.NS",
    "MAX FINANCIAL SERVICES LIMITED": "MFSL.NS",
    "INDIAN ACRYLICS LIMITED": "INDIACRYL.NS",
    "KSS LIMITED": "532444.BO",
    "3I INFOTECH LIMITED": "3IINFOTECH.NS",
    "NALWA SONS INVESTMENTS LIMITED": "NSIL.NS",
    "SUNIL HEALTHCARE LIMITED": "SUNILHF.NS",
    "S H KELKAR AND COMPANY LIMITED": "SHK.NS",
    "SOM DATT FINANCE CORPORATION LTD": "SOMDFIN.BO",
    "SANCIA GLOBAL INFRAPROJECTS LIMITED": "SANGINITA.BO",
    
    # Fifth batch
    "INTERNATIONAL GEMMOLOGICAL INSTITUTE (INDIA) LIMITED": "IGIL.NS",
    "WILLARD INDIA LIMITED": "WILLARDLTD.NS",
    "ZENITH HEALTHCARE LIMITED": "ZHL.NS",
    "HAPPY FORGINGS LIMITED": "HAPPYFORGE.NS",
    "ACTION CONSTRUCTION EQUIPMENT LIMITED": "ACE.NS",
    "SANSTAR LIMITED": "SANSTAR.NS",
    "STEELCO GUJARAT LIMITED": "STEELCO.BO",
    "USHA INDIA LIMITED": "USHAMART.NS",
    "NIPPON INDIA MUTUAL FUND ETF LIQUID BeES": "LIQUIDBEES.NS",
    "CIE AUTOMOTIVE INDIA LIMITED": "CIEINDIA.NS",
    "INDIA CEMENTS LIMITED": "INDIACEM.NS",
    "TEAM INDIA GUARANTY LIMITED": "TEAMGTY.NS",
    "CANARA ROBECO ASSET MANAGEMENT CO. LTD.": "CRAMC.NS",
    "HEXAWARE TECHNOLOGIES LIMITED": "HEXT.NS",
    "ZYLOG SYSTEMS LIMITED": "ZYLOG.NS",
    "GAMMON INDIA LIMITED": "GAMMONIND.NS",
    "ORBIT CORPORATION LIMITED": "ORBITCO.BO",
    "SOUTH ASIAN ENTERPRISES LIMITED": "SAEL.BO",
    "DIVI'S LABORATORIES LIMITED": "DIVISLAB.NS",
    "HEUBACH COLORANTS INDIA LIMITED": "HEUBACHIND.NS",
    "NEXTGEN ANIMATION MEDIAA LIMITED": "532999.BO",
    "PROMACT IMPEX LIMITED": "531174.BO",
    "RURAL ELECTRIFICATION CORPORATION LIMITED": "RECLTD.NS",
    "ICICI PRUDENTIAL MUTUAL FUND BSE LIQUID ETF IDCW": "LIQUIDIETF.NS",
    "INNOVA CAPTAB LIMITED": "INNOVACAP.NS",
    "SBI HOME FINANCE LIMITED": "500379.BO",
    "REI AGRO LIMITED": "REIAGROLTD.NS",
    "GANESH INFRAWORLD LIMITED": "GANESHIN.NS",
    "ESSAR PORTS LIMITED": "ESSARSHPNG.NS",
    "VIKRAM SOLAR LIMITED": "VIKRAMSOLR.NS",
    "REGAAL RESOURCES LIMITED": "539958.BO",
    "GUJARAT PETROSYNTHESE LIMITED": "GUJPETRO.BO",
    "VISU INTERNATIONAL LIMITED": "VISUINTL.BO",
    "EMPIRE INDUSTRIES LIMITED": "EMPIND.NS",
    "HYUNDAI MOTOR INDIA LIMITED": "HYUNDAI.NS",
    "LUMAX AUTO TECHNOLOGIES LIMITED": "LUMAXTECH.NS",
    "PASUPATI ACRYLON LIMITED": "PASUPTAC.NS",
    "MAFATLAL INDUSTRIES LIMITED": "MAFATIND.NS",
    "INDIA PESTICIDES LIMITED.": "IPL.NS",
    "GUJARAT MINERAL DEVELOPMENT CORPORATION LIMITED": "GMDCLTD.NS",
    "PIRAMAL PHARMA LIMITED": "PPLPHARMA.NS",
    "KIRLOSKAR FERROUS INDUSTRIES LTD": "KIRLOSFER.NS",
    "ANIL LIMITED": "ANIL.NS",
    "SAMVARDHANA MOTHERSON INTERNATIONAL LIMITED": "MOTHERSON.NS",
    "MAX INDIA LIMITED": "MAXIND.NS",
    "LARSEN AND TOUBRO LIMITED": "LT.NS",
    "IFSL LIMITED": "POONAWALLA.NS",
    "MAHINDRA AND MAHINDRA FINANCIAL SERVICES LIMITED": "M&MFIN.NS",
    "SUPREME PETROCHEM LIMITED": "SPLPETRO.NS",
    "ION EXCHANGE (INDIA) LIMITED": "IONEXCHANG.NS",
    "GUJARAT STATE FERTILIZERS & CHEMICALS LIMITED": "GSFC.NS",
    "SHREE RENUKA SUGARS LIMITED": "RENUKA.NS",
    "INDEGENE LTD.": "INDEGENE.NS",
    "PAE LIMITED": "PAEL.NS",
    "SHALIMAR WIRES INDUSTRIES LIMITED": "SHALWIRE.BO",
    
    # Sixth batch
    "KHAITAN CHEMICALS AND FERTILIZERS LIMITED": "KHAICHEM.NS",
    "HINDUSTAN UNILEVER LTD.": "HINDUNILVR.NS",
    "MORGANITE CRUCIBLE (INDIA) LIMITED": "MORGANITE.BO",
    "COMMEX TECHNOLOGY LIMITED": "COMMEXTECH.BO",
    "HIMATSINGKA SEIDE LIMITED": "HIMATSEIDE.NS",
    "NATIONAL HIGHWAYS AUTHORITY OF INDIA SR IIB 7.6 BD 11JN31 FVRS1000": "NHIT.NS",
    "LANCO INFRATECH LIMITED": "LITL.NS",
    "INVENTURUS KNOWLEDGE SOLUTIONS LIMITED": "IKS.NS",
    "POCHIRAJU INDUSTRIES LIMITED": "POCHIRAJU.BO",
    "ELECTROSTEEL CASTINGS LIMITED": "ELECTCAST.NS",
    "AMBALAL SARABHAI ENTERPRISES LIMITED": "ASAL.NS",
    "PDS LIMITED": "PDSL.NS",
    "KOTHARI FERMENTATION AND BIOCHEM LIMITED": "507474.BO",
    "HDB FINANCIAL SERVICES LIMITED": "HDBFS.NS",
    "BANSWARA SYNTEX LIMITED": "BANSWRAS.NS",
    "SILVERLINE TECHNOLOGIES LIMITED": "SILVERLINE.NS",
    "ADITYA BIRLA SUN LIFE AMC LIMITED": "ABSLAMC.NS",
    "RAAJRATNA METAL INDUSTRIES LTD. PREF 17JL23": "RAAJRATNA.BO",
    
    # Seventh batch
    "DIAMOND POWER INFRASTRUCTURE LIMITED": "DIAPOWER.NS",
    "STL NETWORKS LIMITED": "STLNETWORK.NS",
    "STURDY INDUSTRIES LIMITED": "STURDY.BO",
    "PEARL GLOBAL INDUSTRIES LIMITED": "PGIL.NS",
    "MANALI PETROCHEMICAL LIMITED": "MANALIPETC.NS",
    "THE LAKSHMI VILAS BANK LIMITED": "LAKSHVILASB.BO",
    "APTECH LIMITED": "APTECHT.NS",
    "EMCURE PHARMACEUTICALS LIMITED": "EMCURE.NS",
    "ESS DEE ALUMINIUM LIMITED": "ESSDEE.NS",
    "JHAGADIA COPPER LIMITED": "JHAGCOP.BO",
    "RATHI ISPAT LIMITED": "RATHISPA.BO",
    "GUJARAT FLUOROCHEMICALS LIMITED": "FLUOROCHEM.NS",
    "IMEC SERVICES LIMITED": "IMEC.BO",
    "GODREJ AGROVET LIMITED": "GODREJAGRO.NS",
    "VIDEOCON INDUSTRIES LIMITED": "VIDEOIND.NS",
    
    # Eighth batch
    "ICICI PRUDENTIAL MUTUAL FUND BHARAT 22 ETF": "ICICIB22.NS",
    "MUKAT PIPES LIMITED": "MUKATPIPE.BO",
    "GOL OFFSHORE LIMITED": "GTOFFSHORE.NS",
    "SOUTHERN HERBALS LIMITED": "SOUTHNHERB.NS",
    "NAYARA ENERGY LIMITED": "ESSAROIL.NS",
    "3I INFOTECH LIMITED REs": "3IINFOLTD.NS",
    "JUBILANT PHARMOVA LIMITED": "JUBLPHARMA.NS",
    "SYNCOM FORMULATIONS (INDIA) LIMITED": "SYNCOMF.NS",
    "V L S FINANCE LIMITED": "VLSFINANCE.NS",
    "BINANI INDUSTRIES LIMITED": "BILVYAPAR.NS",
    "CAPRIHANS INDIA LIMITED": "CAPRIHANS.BO",
    "INDUS TOWERS LIMITED": "INDUSTOWER.NS",
    "EXPO ENGINEERING AND PROJECTS LIMITED": "EXPOGAS.BO",
    "GODAWARI POWER AND ISPAT LIMITED": "GPIL.NS",
    "LML LIMITED": "LML.NS",
    "RATHI STEEL AND POWER LIMITED": "RATHIST.BO",
    "ZYDUS LIFESCIENCES LIMITED": "ZYDUSLIFE.NS",
    
    # Ninth batch (from second document)
    "TD POWER SYSTEMS LIMITED": "TDPOWERSYS.NS",
    "ANTHEM BIOSCIENCES LIMITED": "ANTHEM.NS",
    "EROS INTERNATIONAL MEDIA LIMITED": "EROSMEDIA.NS",
    "GE VERNOVA T&D INDIA LIMITED": "GETD.NS",
    "ORG INFORMATICS LIMITED": "ORGINFO.BO",
    "AVON CORPORATION LIMITED": "531398.BO",
    "IVRCL LIMITED": "IVRCLINFRA.NS",
    "MODERN INSULATORS LIMITED": "515008.BO",
    "RAMKRISHNA FORGINGS LTD": "RKFORGE.NS",
    "REMI EDELSTAHL TUBULARS LIMITED": "REMIESPT.BO",
    "AIA ENGINEERING LTD.": "AIAENG.NS",
    "ELGI EQUIPMENTS LIMITED": "ELGIEQUIP.NS",
    "BIRLA COTSYN (INDIA) LIMITED": "BIRLACOT.NS",
    "PENINSULA LAND LIMITED": "PENINLAND.NS",
    "PHAARMASIA LIMITED": "PHAARMASIA.BO",
    "INTEGRA ESSENTIA LIMITED": "ESSENTIA.NS",
    "THAMBBI MODERN SPINNING MILLS LIMITED": "THAMBBI.BO",
    "SHRISTI INFRASTRUCTURE DEVELOPMENT CORPORATION LIMITED": "SHRISTI.BO",
    "EXPLEO SOLUTIONS LTD.": "EXPLEOSOL.NS",
    "PIDILITE INDUSTRIES LTD.": "PIDILITIND.NS",
    "KAASHYAP TECHNOLOGIES LIMITED": "532283.BO",
    "MTAR TECHNOLOGIES LTD.": "MTARTECH.NS",
    "LAN ESEDA INDUSTRIES LIMITED": "531300.BO",
    "HINDUSTAN ORGANIC CHEMICALS LIMITED": "HOCL.NS",
    "SAMMAAN FINSERVE LIMITED SR VII CAT III & IV 9.2 LOA 25SP28 FVRS1000": "SAMMAANCAP.NS",
    "ORIENTAL AROMATICS LIMITED": "OAL.NS",
    "SICAGEN INDIA LIMITED": "SICAGEN.NS",
    "GUJARAT NRE COKE LIMITED": "GUJNREDVR-EQ.NS",
    "ALOK INDUSTRIES LIMITED": "ALOKINDS.NS",
    "BELRISE INDUSTRIES LIMITED": "513222.BO",
    "HINDOOSTAN MILLS LIMITED": "HINDMILL.NS",
    "VRL LOGISTICS LIMITED": "VRLLOG.NS",
    "STANROSE MAFATLAL INVESTMENTS AND FINANCE LIMITED": "STANROSE.BO",
    "TRANSINDIA REAL ESTATE LIMITED": "TIREL.NS",
    "TRANSPORT CORPORATION OF INDIA LIMITED": "TCI.NS",
    "NOVARTIS INDIA LIMITED": "NOVARTIND.NS",
    "ELANTAS BECK INDIA LIMITED": "ELANTAS.NS",
    "FUTURISTIC OFFSHORE SERVICES AND CHEMICAL LIMITED": "500154.BO",
    
    # Tenth batch
    "JYOTI LIMITED": "JYOTI.BO",
    "HOUSING AND URBAN DEVELOPMENT CORPORATION LIMITED": "HUDCO.NS",
    "SYNCOM HEALTHCARE LIMITED": "SYNCOM.BO",
    "CLENON ENTERPRISES LIMITED": "CLENON.BO",
    "MORGANITE CRUCIBLE (INDIA) LTD": "MORGANITE.BO",
    "PCS TECHNOLOGY LIMITED": "PCS.BO",
    "SURYACHAKRA POWER CORPORATION LIMITED": "SURYACHARK.BO",
    "NIPPON INDIA MUTUAL FUND CPSE ETF (RGESS)": "CPSEETF.NS",
    "RATTANINDIA ENTERPRISES LTD.": "RTNINDIA.NS",
    "PRITHVI INFORMATION SOLUTIONS LTD": "PRITHVI-BZ.NS",
    "NOVA STEELS (INDIA) LIMITED": "NOVIS.BO",
    "WELSPUN LIVING LIMITED": "WELSPUNLIV.NS",
    "JSW CEMENT LIMITED": "JSWCEMENT.NS",
    "SHAHI SHIPPING LIMITED": "SHAHISHIP.BO",
    "SESHAASAI TECHNOLOGIES LIMITED": "SESHAASAI.NS",
    "NORTHERN ARC CAPITAL LIMITED": "NORTHARC.NS",
    "SURYA PHARMACEUTICAL LIMITED": "SURYAPHARM-BZ.NS",
    "NATCO PHARMA LTD": "NATCOPHARM.NS",
    "VIJAY TEXTILES LIMITED": "VIJAYTX.BO",
    "ICICI PRUDENTIAL BSE LIQUID": "LIQUIDIETF.NS",
    "MIC ELECTRONICS LIMITED": "MICEL.NS",
    "ESSAR SHIPPING LIMITED": "ESSARSHPNG.NS",
    "CONCURRENT (I) INFRASTRUCTURE LTD": "CONINFRAT.BO",
    "RADHE DEVELOPERS (INDIA) LIMITED": "RADHE.NS",
    "EASUN REYROLLE LIMITED": "EASUNREYRL.NS",
    "PARAMOUNT COSMETICS (INDIA) LIMITED": "PARCOSMT.BO",
    "LOTUS CHOCOLATE COMPANY LIMITED": "LOTUSCHOCO.NS",
    "YASH MANAGEMENT & SATELLITE LIMITED": "YASHMGM.BO",
    "ARCHEAN CHEMICAL INDUSTRIES LTD.": "ACI.NS",
    "BANSISONS TEA INDUSTRIES LIMITED": "514266.BO",
    "ATV PROJECTS INDIA LIMITED": "ATVPROJ.NS",
    "SARASWATI SAREE DEPOT LIMITED": "540632.BO",
}

def clean_security_name(name):
    """Clean security name to match format in existing mappings"""
    # Remove common suffixes
    name = re.sub(r'\s+EQ\s+EQ$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+EQ$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+NEW\s+.*$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+F\.?V\.?\s+.*$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+SR\s+.*$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+PREF\s+.*$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+REs\s+.*$', '', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+LIMITED\s+.*$', ' LIMITED', name, flags=re.IGNORECASE)
    name = re.sub(r'\s+LTD\.?\s+.*$', ' LTD', name, flags=re.IGNORECASE)
    name = name.strip()
    return name

# Merge mappings
print("\nMerging mappings...")
merged_mappings = existing_mappings.copy()
new_count = 0
updated_count = 0

for security, ticker in new_mappings.items():
    clean_name = clean_security_name(security)
    
    # Check if it's a new mapping or update
    if clean_name not in merged_mappings:
        merged_mappings[clean_name] = ticker
        new_count += 1
        print(f"  + NEW: {clean_name[:60]:60s} -> {ticker}")
    elif merged_mappings[clean_name] != ticker:
        print(f"  ~ UPD: {clean_name[:60]:60s} -> {ticker} (was: {merged_mappings[clean_name]})")
        merged_mappings[clean_name] = ticker
        updated_count += 1

# Save updated mappings
print(f"\nSaving updated mappings...")
with open('manual_ticker_mappings.json', 'w') as f:
    json.dump(merged_mappings, f, indent=2, sort_keys=True)

print(f"\n{'='*80}")
print("SUMMARY")
print(f"{'='*80}")
print(f"  Original mappings: {len(existing_mappings)}")
print(f"  New mappings added: {new_count}")
print(f"  Mappings updated: {updated_count}")
print(f"  Total mappings now: {len(merged_mappings)}")
print(f"{'='*80}\n")

print("✅ Manual ticker mappings updated successfully!")
print("   File: manual_ticker_mappings.json")
